=== lrodriolivera/luci-customs-agent/docs/nl-migs/DECO-2.0/MIG DECO 2.0/Section 2 (B2DECO)/2. XmlSchema/2. AddMes/1. WithoutNotes/DECO.AdditionalMessage_2p00.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:wco:datamodel:WCO:DECO.AdditionalMessage:2"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:ds="urn:wco:datamodel:WCO:DMSDECO.OverallModel_DS:2"
    targetNamespace="urn:wco:datamodel:WCO:DECO.AdditionalMessage:2"
    elementFormDefault="qualified">
  <xs:import namespace="urn:wco:datamodel:WCO:DMSDECO.OverallModel_DS:2" schemaLocation="DECO.OverallModel_DS_2p00.xsd"/>
  <xs:element name="MetaData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="WCOTypeCode" type="ds:MetaDataWCOTypeCodeType"/>
        <xs:element name="CommunicationMetaData">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ApplicationReferenceID" type="ds:CommunicationMetaDataApplicationReferenceIDType"/>
              <xs:element name="CommunicationsAgreementID" type="ds:CommunicationMetaDataCommunicationsAgreementIDType" minOccurs="0"/>
              <xs:element name="PreparationDateTime" type="ds:CommunicationMetaDataPreparationDateTimeType"/>
              <xs:element name="Recipient">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ID" type="ds:RecipientIdentificationIDType"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Sender">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ID" type="ds:SenderIdentificationIDType"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Declaration">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="FunctionalReferenceID" type="ds:DeclarationFunctionalReferenceIDType" minOccurs="0"/>
              <xs:element name="ID" type="ds:DeclarationIdentificationIDType" minOccurs="0"/>
              <xs:element name="IssueDateTime" type="ds:DeclarationIssueDateTimeType" minOccurs="0"/>
              <xs:element name="DeclarationOffice" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ID" type="ds:DeclarationOfficeIdentificationIDType" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="AdditionalInformation" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="SequenceNumeric" type="ds:AdditionalInformationSequenceNumericType" minOccurs="0"/>
                    <xs:element name="StatementCode" type="ds:AdditionalInformationStatementCodeType" minOccurs="0"/>
                    <xs:element name="StatementDescription" type="ds:AdditionalInformationStatementDescriptionTextType" minOccurs="0"/>
                    <xs:element name="StatementTypeCode" type="ds:AdditionalInformationStatementTypeCodeType" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Agent" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ID" type="ds:AgentIdentificationIDType" minOccurs="0"/>
                    <xs:element name="FunctionCode" type="ds:AgentFunctionCodeType" minOccurs="0"/>
                    <xs:element name="Contact" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="ds:ContactNameTextType" minOccurs="0"/>
                          <xs:element name="Communication" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="SequenceNumeric" type="ds:CommunicationSequenceNumericType" minOccurs="0"/>
                                <xs:element name="ID" type="ds:CommunicationIdentificationIDType" minOccurs="0"/>
                                <xs:element name="TypeCode" type="ds:CommunicationTypeCodeType" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Declarant" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="ds:DeclarantNameTextType" minOccurs="0"/>
                    <xs:element name="ID" type="ds:DeclarantIdentificationIDType" minOccurs="0"/>
                    <xs:element name="Address" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="CityName" type="ds:AddressCityNameTextType" minOccurs="0"/>
                          <xs:element name="CountryCode" type="ds:AddressCountryCodeType" minOccurs="0"/>
                          <xs:element name="Line" type="ds:AddressLineTextType" minOccurs="0"/>
                          <xs:element name="PostcodeID" type="ds:AddressPostcodeIDType" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Contact" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="ds:ContactNameTextType" minOccurs="0"/>
                          <xs:element name="Communication" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="SequenceNumeric" type="ds:CommunicationSequenceNumericType" minOccurs="0"/>
                                <xs:element name="ID" type="ds:CommunicationIdentificationIDType" minOccurs="0"/>
                                <xs:element name="TypeCode" type="ds:CommunicationTypeCodeType" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lrodriolivera/luci-customs-agent/docs/nl-migs/DECO-2.0/MIG DECO 2.0/Section 2 (B2DECO)/2. XmlSchema/2. AddMes/1. WithoutNotes/DECO.AdditionalMessageExample_2p00.xml
<?xml version="1.0" encoding="UTF-8"?>
<MetaData xmlns="urn:wco:datamodel:WCO:DECO.AdditionalMessage:2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:wco:datamodel:WCO:DECO.AdditionalMessage:2 DECO.AdditionalMessage_2p00.xsd">
  <WCOTypeCode>123456</WCOTypeCode>
  <CommunicationMetaData>
    <ApplicationReferenceID>XXXXXXXXXX</ApplicationReferenceID>
    <CommunicationsAgreementID>XXXXXXXXXX</CommunicationsAgreementID>
    <PreparationDateTime formatCode="304">20200723143432Z</PreparationDateTime>
    <Recipient>
      <ID>XXXXXXXXXXXXXXXXX</ID>
    </Recipient>
    <Sender>
      <ID>XXXXXXXXXXXXXXXXX</ID>
    </Sender>
  </CommunicationMetaData>
  <Declaration>
    <FunctionalReferenceID>XXXXXXXXXX</FunctionalReferenceID>
    <ID>XXXXXXXXXX</ID>
    <IssueDateTime formatCode="304">20200723143432Z</IssueDateTime>
    <DeclarationOffice>
      <ID>XXXXXXXXXX</ID>
    </DeclarationOffice>
    <AdditionalInformation>
      <SequenceNumeric>23</SequenceNumeric>
      <StatementCode>XXXXXXXXXX</StatementCode>
      <StatementDescription>XXXXXXXXXX</StatementDescription>
      <StatementTypeCode>ADE</StatementTypeCode>
    </AdditionalInformation>
    <Agent>
      <ID>XXXXXXXXXX</ID>
      <FunctionCode>90</FunctionCode>
      <Contact>
        <Name>XXXXXXXXXX</Name>
        <Communication>
          <SequenceNumeric>23</SequenceNumeric>
          <ID>XXXXXXXXXX</ID>
          <TypeCode>TM</TypeCode>
        </Communication>
      </Contact>
    </Agent>
    <Declarant>
      <Name>XXXXXXXXXX</Name>
      <ID>XXXXXXXXXX</ID>
      <Address>
        <CityName>XXXXXXXXXX</CityName>
        <CountryCode>KZ</CountryCode>
        <Line>XXXXXXXXXX</Line>
        <PostcodeID>XXXXXXXXXX</PostcodeID>
      </Address>
      <Contact>
        <Name>XXXXXXXXXX</Name>
        <Communication>
          <SequenceNumeric>23</SequenceNumeric>
          <ID>XXXXXXXXXX</ID>
          <TypeCode>AB</TypeCode>
        </Communication>
      </Contact>
    </Declarant>
  </Declaration>
</MetaData>
